#!/bin/bash
cd /home/pi/project
source project/bin/activate
python camera.py

chmod +x run_camera.sh

0 * * * * /home/pi/my_project/run_camera.sh >> /home/pi/my_project/camera.log 2>&1





0 * * * * /bin/bash -c 'cd /home/pi/my_project && source project/bin/activate && python camera.py >> camera.log 2>&1'
